Feat: Power Consumed Watts functionality added (barebones)
redhat-performance/badfish pull request #331
Opened 2022-10-07 15:45 UTC by QuantumPosix

2022-10-11 13:55 UTC, QuantumPosix commented
fixes #309

2022-10-14 14:15 UTC, grafuls commented on src/badfish/main.py
> +
remove extra line

2022-12-09 12:03 UTC, grafuls requested changes
Include tests

2022-12-09 17:11 UTC, sadsfae approved these changes
Nice beginnings of power awareness with Badfish.  I'd expect to be able to build on this to create polling intervals and do the backend math on average / high / low over a reasonable polling period.

2022-12-13 14:00 UTC, merged