feat: add chat webhooks for issues/push events.
redhat-performance/badfish pull request #344
Opened 2023-01-26 15:16 UTC by sadsfae

* This adds two GHA for accessing repo secrets to push chat notifications via webhooks for:
  - new issue creation
  - push events via https://github.com/marketplace/actions/workflow-webhook-action

2023-01-31 14:33 UTC, sadsfae commented
Strangely, I don't see this in Matrix at all but I do see them in G-chat.

2023-02-07 13:59 UTC, grafuls requested changes

2023-02-07 13:59 UTC, grafuls commented on .github/workflows/issuetracker-webhook.yml
> +            --data-raw '{
replace this with:
```
--data "{'text': '[${{ github.event.issue.number }}] ${{ github.event.issue.title }} (${{ github.event.issue.user.login }})'}"
```

2023-02-08 08:49 UTC, grafuls approved these changes

2023-02-08 08:50 UTC, merged